version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
#       - image: circleci/php:5.6-apache-node-browsers
      - image: notnoopci/php:7.1.5-browsers
    steps:
      - checkout
      - run: ls
      - run: pwd -P
      - run: cd public
      - run: ls
      - run: pwd -P
      - run: composer self-update
      - run: composer global require wp-cli
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
#      - run: composer init-phpcs
#      - run: composer test


